//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string InviteCode { get; set; }
        public string InviteCodeUser { get; set; }
        public Nullable<System.DateTime> InviteCodeDatetime { get; set; }
        public string InviteCode2 { get; set; }
        public string InviteCode2User { get; set; }
        public Nullable<System.DateTime> InviteCode2Datetime { get; set; }
        public string LogonIP { get; set; }
        public string MyName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string AnmeldenProvince { get; set; }
        public string AnmeldenCity { get; set; }
        public string LiveProvince { get; set; }
        public string LiveCity { get; set; }
        public string PersonalAssessment { get; set; }
        public string Email { get; set; }
        public Nullable<int> Sort { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public byte[] Version { get; set; }
    }
}
