//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> CommentNumber { get; set; }
        public Nullable<int> ReadNumber { get; set; }
        public string Picture3 { get; set; }
        public string Picture2 { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Sort { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public byte[] Version { get; set; }
        public string Abstract { get; set; }
        public string PictureName { get; set; }
        public string Picture2Name { get; set; }
        public string Picture3Name { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
